[package]
name = "gambling_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
rand = "0.8.5"
rand_derive = "0.5.0"
raylib = "5.0.0"
weighted_rand = "0.4.2"
